### ISSUE TITLE
Replace individual button presses with a lambda function

### ISSUE THREAD

**Issue by scotty3785** [piborg/SpaceBorgOne#1]
Great example of a Tkinter gui and use of threading.

Thought I'd let you know of a more efficient way to deal with the different button presses on commandCentre.py. You can use a lambda function to pass a parameter to a common 'button press function'

`direction = 'FD'`
`command_function = lambda x=direction: self.AddMove(x)`
`self.butForward = Tkinter.Button(self, text = '↑', command = command_function)`

**Comment by piborg** [comment]
Lambda functions for the buttons is a great idea and saves a lot of lines of code.

I have simplified the calls down to a lambda with no variables like this:
`self.but1 = Tkinter.Button(self, text = '1', command = lambda: self.AddNumber(1))`
